version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: tennis_db
    ports:
      - "6432:5432"
    volumes:
      - postgres_tennis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tennis_db"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  postgres_tennis_data: