
--
---- ФАКТ: Статистика игроков в матче
--CREATE TABLE ods.fct_matches (
--    id SERIAL PRIMARY KEY,
--    datetime DATETIME ,
--    match_id VARCHAR(50),
--    tour VARCHAR(255),
--    round VARCHAR(255),
--    player_id VARCHAR(50),
--    player_name VARCHAR(100),
--    player_rank INTEGER,
--    player_odd NUMERIC(6,2)
--    is_player_one BOOLEAN,
--    is_winner BOOLEAN,
--    wins_in_last_5_games INTEGER,
--    wins_in_h2h INTEGER,
--    result_score VARCHAR(50),
--    aces INTEGER,
--    double_faults INTEGER,
--    first_serve_percentage INTEGER,
--    first_serve_in INTEGER,
--    first_serve_points_won INTEGER,
--    first_serve_points_total INTEGER,
--    second_serve_points_won INTEGER,
--    second_serve_points_total INTEGER,
--    break_points_saved INTEGER,
--    break_points_total INTEGER,
--    first_return_points_won INTEGER,
--    first_return_points_total INTEGER,
--    second_return_points_won INTEGER,
--    second_return_points_total INTEGER,
--    break_points_converted INTEGER,
--    break_points_converted_total INTEGER,
--    service_points_won INTEGER,
--    service_points_total INTEGER,
--    return_points_won INTEGER,
--    return_points_total INTEGER,
--    total_points_won INTEGER,
--    total_points_total INTEGER,
--    last_10_balls_won INTEGER,
--    match_points_saved INTEGER,
--    service_games_won INTEGER,
--    service_games_total INTEGER,
--    return_games_won INTEGER,
--    return_games_total INTEGER,
--    total_games_won INTEGER,
--    total_games_total INTEGER


CREATE TABLE IF NOT EXISTS ods.fct_matches (
    game_id VARCHAR(50) PRIMARY KEY,
    tour VARCHAR(100),
    round VARCHAR(100),
    datetime VARCHAR(20),
    player_id_home VARCHAR(20),
    player_link_home TEXT,
    player_name_home VARCHAR(100),
    player_rank_home INTEGER,
    player_id_away VARCHAR(20),
    player_link_away TEXT,
    player_name_away VARCHAR(100),
    player_rank_away INTEGER,
    player_odd_home NUMERIC(4,2),
    player_odd_away NUMERIC(4,2),
    wins_in_last_5_games_home INTEGER,
    wins_in_last_5_games_away INTEGER,
    wins_in_h2h_home INTEGER,
    wins_in_h2h_away INTEGER,
    is_winner_home BOOLEAN,
    is_winner_away BOOLEAN,
    result_score_home TEXT,
    result_score_away TEXT,
    aces_home INTEGER,
    aces_away INTEGER,
    double_faults_home INTEGER,
    double_faults_away INTEGER,
    first_serve_percentage_home INTEGER,
    first_serve_percentage_away INTEGER,
    first_serve_points_won_home INTEGER,
    first_serve_points_total_home INTEGER,
    first_serve_points_won_away INTEGER,
    first_serve_points_total_away INTEGER,
    second_serve_points_won_home INTEGER,
    second_serve_points_total_home INTEGER,
    second_serve_points_won_away INTEGER,
    second_serve_points_total_away INTEGER,
    break_points_saved_home INTEGER,
    break_points_total_home INTEGER,
    break_points_saved_away INTEGER,
    break_points_total_away INTEGER,
    first_return_points_won_home INTEGER,
    first_return_points_total_home INTEGER,
    first_return_points_won_away INTEGER,
    first_return_points_total_away INTEGER,
    second_return_points_won_home INTEGER,
    second_return_points_total_home INTEGER,
    second_return_points_won_away INTEGER,
    second_return_points_total_away INTEGER,
    break_points_converted_home INTEGER,
    break_points_converted_total_home INTEGER,
    break_points_converted_away INTEGER,
    break_points_converted_total_away INTEGER,
    service_points_won_home INTEGER,
    service_points_total_home INTEGER,
    service_points_won_away INTEGER,
    service_points_total_away INTEGER,
    return_points_won_home INTEGER,
    return_points_total_home INTEGER,
    return_points_won_away INTEGER,
    return_points_total_away INTEGER,
    total_points_won_home INTEGER,
    total_points_total_home INTEGER,
    total_points_won_away INTEGER,
    total_points_total_away INTEGER,
    last_10_balls_won_home INTEGER,
    last_10_balls_won_away INTEGER,
    match_points_saved_home INTEGER,
    match_points_saved_away INTEGER,
    service_games_won_home INTEGER,
    service_games_total_home INTEGER,
    service_games_won_away INTEGER,
    service_games_total_away INTEGER,
    return_games_won_home INTEGER,
    return_games_total_home INTEGER,
    return_games_won_away INTEGER,
    return_games_total_away INTEGER,
    total_games_won_home INTEGER,
    total_games_total_home INTEGER,
    total_games_won_away INTEGER,
    total_games_total_away INTEGER

);
COMMENT ON TABLE ods.fct_matches IS 'Детальная статистика игрока в матче';
